### ISSUE TITLE
split in two unequally ?

### ISSUE THREAD

**Issue by sam217pa** [IvanMalison/tile#2]
Hi and thanks for this great package, it really is part of my workflow now.
I'm having trouble to get it to do exactly what I want though. 

I'd like to be able to split the screen in two, one part occupying two third of the screen.

Maybe there is a simple strategy to do that but I wasn't able to find it ?

Thanks for your help !

**Comment by colonelpanic8** [comment]
You will probably need to create a custom tile strategy that calls enlarge-window-horizontally after splitting.
Something like:
``` emacs-lisp
(defvar tile-master-big-left
  (tile-master-layout
   :master-fn (lambda () (split-window-horizontally) (enlarge-window-horizontally 40) (other-window 1))
   :other-fn 'split-window-vertically)
```

**Comment by colonelpanic8** [comment]
@sam217pa I'm going to close for now. Let me know if that does what you want
